#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-simplecov-html
Version  : 0.10.0
Release  : 3
URL      : https://rubygems.org/downloads/simplecov-html-0.10.0.gem
Source0  : https://rubygems.org/downloads/simplecov-html-0.10.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Default HTML formatter for SimpleCov
====================================
***Note: To learn more about SimpleCov, check out the main repo at https://github.com/colszowka/simplecov***

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n simplecov-html-0.10.0
gem spec %{SOURCE0} -l --ruby > rubygem-simplecov-html.gemspec

%build
gem build rubygem-simplecov-html.gemspec

%install
gem_dir=$(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .${gem_dir} \
--bindir .%{_bindir} \
simplecov-html-0.10.0.gem

mkdir -p %{buildroot}${gem_dir}
cp -pa .${gem_dir}/* \
%{buildroot}${gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/simplecov-html-0.10.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/asset_output_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/assets_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/cdesc-HTMLFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/coverage_css_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/formatted_file_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/formatted_source_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/link_to_source_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/output_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/output_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/shortened_filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/strength_css_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/template-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/HTMLFormatter/timeago-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/Formatter/cdesc-Formatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/SimpleCov/cdesc-SimpleCov.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-html-0.10.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/.document
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/.rubocop.yml
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/application.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/libraries/jquery-1.6.2.min.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/plugins/highlight.pack.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/plugins/jquery.colorbox.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/plugins/jquery.dataTables.min.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/plugins/jquery.timeago.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/javascripts/plugins/jquery.url.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/application.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/plugins/highlight.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/plugins/jquery-ui-1.8.4.custom.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/plugins/jquery.colorbox.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/reset.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/assets/stylesheets/screen.css.sass
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/lib/simplecov-html/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/application.css
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/application.js
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/colorbox/border.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/colorbox/controls.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/colorbox/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/colorbox/loading_background.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/favicon_green.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/favicon_red.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/favicon_yellow.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/magnify.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_glass_75_dadada_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-icons_222222_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-icons_2e83ff_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-icons_454545_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-icons_888888_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/public/smoothness/images/ui-icons_cd0a0a_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/simplecov-html.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/test/test_simple_cov-html.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/views/file_list.erb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/views/layout.erb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-html-0.10.0/views/source_file.erb
/usr/lib64/ruby/gems/2.2.0/specifications/simplecov-html-0.10.0.gemspec
